# Database Configuration (Using H2 for ease of testing, can be swapped for PostgreSQL easily)
spring.datasource.url=jdbc:h2:mem:shippingdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console (available at /h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.port=8080

spring.jpa.defer-datasource-initialization=true